/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attachment: typeof import('./components/Attachment.vue')['default']
    BrowseLessonPack: typeof import('./components/BrowseLessonPack.vue')['default']
    BrowseLessonPacks: typeof import('./components/BrowseLessonPacks.vue')['default']
    Fa6SolidUsersLine: typeof import('~icons/fa6-solid/users-line')['default']
    FlashCard: typeof import('./components/FlashCard.vue')['default']
    HealthiconsIExamMultipleChoiceNegative: typeof import('~icons/healthicons/i-exam-multiple-choice-negative')['default']
    IcBaselinePlus: typeof import('~icons/ic/baseline-plus')['default']
    IconamoonMenuBurgerHorizontalBold: typeof import('~icons/iconamoon/menu-burger-horizontal-bold')['default']
    IcRoundDashboard: typeof import('~icons/ic/round-dashboard')['default']
    IcSharpMenuBook: typeof import('~icons/ic/sharp-menu-book')['default']
    MakiCross: typeof import('~icons/maki/cross')['default']
    MaterialSymbolsDashboard: typeof import('~icons/material-symbols/dashboard')['default']
    MaterialSymbolsEditDocumentRounded: typeof import('~icons/material-symbols/edit-document-rounded')['default']
    MaterialSymbolsNotifications: typeof import('~icons/material-symbols/notifications')['default']
    MaterialSymbolsPlayCircleOutline: typeof import('~icons/material-symbols/play-circle-outline')['default']
    MaterialSymbolsShoppingCartOutlineRounded: typeof import('~icons/material-symbols/shopping-cart-outline-rounded')['default']
    MaterialSymbolsToggleOffOutline: typeof import('~icons/material-symbols/toggle-off-outline')['default']
    MaterialSymbolsTrophy: typeof import('~icons/material-symbols/trophy')['default']
    MdiCards: typeof import('~icons/mdi/cards')['default']
    MdiHelpCircle: typeof import('~icons/mdi/help-circle')['default']
    OtherVideo: typeof import('./components/OtherVideo.vue')['default']
    OtherVideos: typeof import('./components/OtherVideos.vue')['default']
    PageHeading: typeof import('./components/common/PageHeading.vue')['default']
    PhSignOutBold: typeof import('~icons/ph/sign-out-bold')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./components/Tab.vue')['default']
    TabsWrapper: typeof import('./components/TabsWrapper.vue')['default']
    VideoQuestion: typeof import('./components/VideoQuestion.vue')['default']
    ZondiconsSend: typeof import('~icons/zondicons/send')['default']
  }
}
