/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attachment: typeof import('./components/Attachment.vue')['default']
    EnrolledClass: typeof import('./components/EnrolledClass.vue')['default']
    Fa6SolidUsersLine: typeof import('~icons/fa6-solid/users-line')['default']
    HealthiconsIExamMultipleChoiceNegative: typeof import('~icons/healthicons/i-exam-multiple-choice-negative')['default']
    IconamoonMenuBurgerHorizontalBold: typeof import('~icons/iconamoon/menu-burger-horizontal-bold')['default']
    IcRoundDashboard: typeof import('~icons/ic/round-dashboard')['default']
    IcSharpMenuBook: typeof import('~icons/ic/sharp-menu-book')['default']
    LessonPack: typeof import('./components/LessonPack.vue')['default']
    MakiCross: typeof import('~icons/maki/cross')['default']
    MaterialSymbolsDashboard: typeof import('~icons/material-symbols/dashboard')['default']
    MaterialSymbolsEditDocumentRounded: typeof import('~icons/material-symbols/edit-document-rounded')['default']
    MaterialSymbolsNotifications: typeof import('~icons/material-symbols/notifications')['default']
    MaterialSymbolsPlayCircleOutline: typeof import('~icons/material-symbols/play-circle-outline')['default']
    MaterialSymbolsShoppingCartOutlineRounded: typeof import('~icons/material-symbols/shopping-cart-outline-rounded')['default']
    MaterialSymbolsToggleOffOutline: typeof import('~icons/material-symbols/toggle-off-outline')['default']
    MaterialSymbolsTrophy: typeof import('~icons/material-symbols/trophy')['default']
    MdiCards: typeof import('~icons/mdi/cards')['default']
    MdiHelpCircle: typeof import('~icons/mdi/help-circle')['default']
    MyLessonPacks: typeof import('./components/MyLessonPacks.vue')['default']
    PageHeading: typeof import('./components/common/PageHeading.vue')['default']
    PhSignOutBold: typeof import('~icons/ph/sign-out-bold')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TutorInfoCard: typeof import('./components/TutorInfoCard.vue')['default']
    VideoQuestion: typeof import('./components/VideoQuestion.vue')['default']
  }
}
